# Generated by Django 4.2.6 on 2023-11-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_academico', models.CharField(max_length=50)),
                ('numero_repitencias', models.IntegerField(default=0)),
                ('tiempo_estudio', models.IntegerField()),
                ('preferencia_profesional', models.CharField(max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alumno')),
            ],
        ),
    ]
