# Generated by Django 4.2.7 on 2023-11-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_psicopedagogo_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='Docente_CONTRASENA',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='psicopedagogo',
            name='Psicopedagogo_CONTRASENA',
        ),
    ]
