# Generated by Django 4.2.7 on 2023-11-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_docente_docente_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alumno')),
                ('psicopedagogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psicopedagogo')),
            ],
        ),
    ]
