# Generated by Django 4.2.7 on 2023-11-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cita'),
        ('main', '0006_informacionextracurricular1_condicionsocioeconomica1_and_more'),
    ]

    operations = [
    ]
