# Generated by Django 4.2.7 on 2023-11-29 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_merge_20231129_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDApoderado', models.CharField(max_length=8, unique=True)),
                ('Nombre_A', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('NivelEducativo', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Instituto', 'Instituto'), ('Universidad', 'Universidad')], max_length=15)),
                ('Profesion', models.CharField(max_length=100)),
                ('CorreoElectronico', models.EmailField(max_length=254, unique=True)),
                ('NumeroTelefono', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
